apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        owner: data-engineer
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      taints:
      - key: nvidia.com/gpu
        value: "Exists"
        effect: "NoSchedule"
      requirements:
      - key: "eks.amazonaws.com/instance-family"
        operator: In
        values: [ "g5", "g6", "g6e", "p5", "p4" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "spot", "on-demand" ]
  limits:
    cpu: "1000"
    memory: 1000Gi
---

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ml-accelerator-nodepool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        owner: data-engineer
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      taints:
      - key: aws.amazon.com/neuron
        value: "true"
        effect: "NoSchedule"
      requirements:
      - key: "eks.amazonaws.com/instance-family"
        operator: In
        values: [ "inf1", "inf2", "trn1", "trn1n" ]
      - key: "kubernetes.io/arch"
        operator: In
        values: [ "amd64" ]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: [ "spot", "on-demand" ]
  limits:
    cpu: "1000"
    memory: 1000Gi
