# https://raw.githubusercontent.com/awslabs/data-on-eks/refs/heads/main/gen-ai/inference/vllm-ray-gpu-deepseek/open-webui.yaml
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: deepseek
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: deepseek
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        # This is the vllm k8s service URL to which Open-WebUI client connects to.
        - name: OPENAI_API_BASE_URLS
          value: "http://deepseek-svc-qwen-32b/v1"
        - name: OPENAI_API_KEY
          value: "dummy" # Replace with actual API key if required
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: deepseek
  labels:
    app: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
