apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: sglang
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
        - name: sglang-leader
          image: lmsysorg/sglang:latest
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: [
            "--model-path", "deepseek-ai/DeepSeek-R1",
            "--host", "0.0.0.0",
            "--port", "8000",
            "--tp", "16",
            "--dist-init-addr", "$(LWS_LEADER_ADDRESS):20000",
            "--nnodes", "$(LWS_GROUP_SIZE)",
            "--node-rank", "$(LWS_WORKER_INDEX)",
            --trust-remote-code,
            "--enable-flashinfer-mla",
            "--enable-p2p-check",
            "--enable-ep-moe",
            "--quantization", "fp8",
            # "--context-length", "8192",
          ]
          resources:
            limits:
              nvidia.com/gpu: "8"
          ports:
          - name: http
            containerPort: 8000
          env:
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          - name: NCCL_DEBUG
            value: "INFO"
          - name: NCCL_P2P_DISABLE
            value: "0"
          - name: NCCL_NVLS_ENABLE
            value: "1"
          - name: NCCL_P2P_LEVEL
            value: "NVL"
          - name: FI_PROVIDER
            value: "efa"
          - name: FI_EFA_USE_DEVICE_RDMA
            value: "1"
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /root/.cache/huggingface
            name: cache-volume
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
        - name: cache-volume
          hostPath:
            path: /tmp/deepseek
            type: DirectoryOrCreate
    workerTemplate:
      spec:
        containers:
        - name: sglang-worker
          image: lmsysorg/sglang:latest
          command: [ "python3", "-m", "sglang.launch_server" ]
          args: [
            "--model-path", "deepseek-ai/DeepSeek-R1",
            "--host", "0.0.0.0",
            "--port", "8000",
            "--tp", "16",
            "--dist-init-addr", "$(LWS_LEADER_ADDRESS):20000",
            "--nnodes", "$(LWS_GROUP_SIZE)",
            "--node-rank", "$(LWS_WORKER_INDEX)",
            --trust-remote-code,
            "--enable-flashinfer-mla",
            "--enable-p2p-check",
            "--enable-ep-moe",
            "--quantization", "fp8",
            # "--context-length", "8192",
          ]
          resources:
            limits:
              nvidia.com/gpu: "8"
          env:
          - name: LWS_WORKER_INDEX
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['leaderworkerset.sigs.k8s.io/worker-index']
          - name: NCCL_DEBUG
            value: "INFO"
          - name: NCCL_P2P_DISABLE
            value: "0"
          - name: NCCL_NVLS_ENABLE
            value: "1"
          - name: NCCL_P2P_LEVEL
            value: "NVL"
          - name: FI_PROVIDER
            value: "efa"
          - name: FI_EFA_USE_DEVICE_RDMA
            value: "1"
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /root/.cache/huggingface
            name: cache-volume
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 100Gi
        - name: cache-volume
          hostPath:
            path: /tmp/deepseek
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: sglang-leader
spec:
  selector:
    leaderworkerset.sigs.k8s.io/name: sglang
    role: leader
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http
