apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-llama-70b-sglang
  namespace: deepseek
  labels:
    app: deepseek-llama-70b
    engine: sglang
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deepseek-llama-70b-sglang
      engine: sglang
  template:
    metadata:
      labels:
        app: deepseek-llama-70b-sglang
        model: deepseek-r1-distill-llama-70b
        engine: sglang
    spec:
      priorityClassName: high-priority-100
      nodeSelector:
        owner: data-engineer
        node.kubernetes.io/instance-type: g6e.12xlarge
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: cache-volume
        hostPath:
          path: /tmp/deepseek
          type: DirectoryOrCreate
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: deepseek
        image: docker.io/lmsysorg/sglang:latest
        imagePullPolicy: Always # IfNotPresent or Never
        command: [ "python3", "-m", "sglang.launch_server" ]
        args: [ "--model-path", "deepseek-ai/DeepSeek-R1-Distill-Llama-70B", "--trust-remote-code", "--tensor-parallel-size", "4", "--host", "0.0.0.0", "--port", "8000", "--disable-custom-all-reduce", "--enable-nccl-nvls", "--context-length", "32768", "--dtype", "bfloat16", "--mem-fraction-static", "0.9" ]
        env:
        - name: NCCL_DEBUG
          value: "INFO"
        - name: NCCL_IB_DISABLE
          value: "1"
        - name: NCCL_P2P_DISABLE
          value: "1"
        # Consider adding these args for better performance:
        # "--max-model-len", "4096",  # Set appropriate context length
        # "--dtype", "bfloat16",      # Use bfloat16 for better efficiency
        # "--gpu-memory-utilization", "0.9"  # Control memory usage
        ports:
        - name: http
          containerPort: 8000
        resources:
          limits:
            cpu: "32"
            memory: 300G
            nvidia.com/gpu: "4"
          requests:
            cpu: "32"
            memory: 300G
            nvidia.com/gpu: "4"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
---

apiVersion: v1
kind: Service
metadata:
  name: deepseek-svc-llama-70b-sglang
spec:
  selector:
    app: deepseek-llama-70b-sglang
    engine: sglang
  ports:
  - protocol: TCP
    port: 80 # port on host
    targetPort: http # port in container
  type: ClusterIP
