apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-llama-8b-sglang
  namespace: deepseek
  labels:
    app: deepseek-llama-8b
    engine: sglang
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: deepseek-llama-8b-sglang
      engine: sglang
  template:
    metadata:
      labels:
        app: deepseek-llama-8b-sglang
        model: deepseek-r1-distill-llama-8b
        engine: sglang
    spec:
      priorityClassName: high-priority-100
      nodeSelector:
        owner: data-engineer
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: deepsek
        image: docker.io/lmsysorg/sglang:latest
        imagePullPolicy: Always # IfNotPresent or Never
        ports:
        - name: http
          containerPort: 8000
        command: [ "python3", "-m", "sglang.launch_server" ]
        args: [ "--model", "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "--host", "0.0.0.0", "--port", "8000" ]
        resources:
          limits:
            cpu: "32"
            memory: 100G
            nvidia.com/gpu: "1"
          requests:
            cpu: "16"
            memory: 30G
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: cache-volume
        hostPath:
          path: /tmp/deepseek
          type: DirectoryOrCreate
---

apiVersion: v1
kind: Service
metadata:
  name: deepseek-svc-llama-8b-sglang
spec:
  selector:
    app: deepseek-llama-8b-sglang
    engine: sglang
  ports:
  - protocol: TCP
    port: 80 # port on host
    targetPort: http # port in container
  type: ClusterIP
